// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxbnmaktyvhlhcjekldm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14Ym5tYWt0eXZobGhjamVrbGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDY5MDUsImV4cCI6MjA3MDQyMjkwNX0.Fn02af3q1THdQUMInZTotgfDW3kI8dCp4f6cQIplJZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});